### ISSUE TITLE
No summary when 2 ot more locations defined

### ISSUE THREAD

**Issue by aku-xima** [black-sheep-dev/harbour-apocalypse#1]
PRECONDITION
two or more locations defined, all locations have Messages/Mitteilungen
the Locations are defined the order is shown below:

Mainz-Biningen ( 1Message)
Dresden (2 Messages)

ACTUAL
Only 2 messages of Dresden are listed in "Local Messages \ Lokale Mitteilungen". Maybe messages of first location are overwriten  by the next defined location?

EXPECTED
When more than 2 locations are defined all messages should be summarized and shown in "Local Messages/Lokale Mitteilungen"

**Comment by black-sheep-dev** [comment]
The problem should be fixed with version 0.1.5.
I check the local position with the polygon geo area information of the message. 
I didn't care about multiple polygons per message.
